service: notifications-service
frameworkVersion: "3"
plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  iam:
    role: ${file(./yml/iam/statements.yml)}

functions:
  sendMail:
    handler: ./src/handlers/sendMail.handler
custom:
  bundle:
    linting: false
