service: notifications-service

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 256
  stage: ${opt:stage, 'dev'}

functions:
  hello:
    handler: ./src/handlers/hello.handler
    events:
      - http:
          method: GET
          path: /hello
custom:
  bundle:
    linting: false
