service: notifications-service
frameworkVersion: "3"
plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  iam:
    role: ${file(./yml/iam/statements.yml)}

resources:
  Resources:
    MailQueue: ${file(./yml/resources/MailQueue.yml):MailQueue}
  Outputs:
    MailQueueArn: ${file(./yml/resources/MailQueue.yml):Outputs.MailQueueArn}
    MailQueueUrl: ${file(./yml/resources/MailQueue.yml):Outputs.MailQueueUrl}

functions:
  sendMail:
    handler: ./src/handlers/sendMail.handler
    events:
      - sqs:
          arn: ${self:custom.mailQueue.arn}
          batchSize: 1
custom:
  mailQueue:
    name: MailQueue-${self:provider.stage}
    arn: !GetAtt MailQueue.Arn
    url: !Ref MailQueue
  bundle:
    linting: false
